# Use root/example as user/password credentials
version: '3.2'

services:

  db:
    image: mongo:4.2
    restart: always
    container_name: db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
